name: Deploy Prod to CF

on:
  release:
    types: [published]
    tags:
      - 'v*'
jobs:
  deploy-prod:
    if: '!github.event.release.prerelease'
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      # Sets node config
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        working-directory: webapp
        run: npm install

      # Build package
      - name: Build
        working-directory: webapp
        run: npm run build
        env:
          CI: false

      # Publish to CF pages
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: voyager-verse-bitcoin-com
          directory: dist
          branch: trunk
          workingDirectory: webapp
          wranglerVersion: '3'

